version: '3.8'

services:
  yue-exllamav2-interface :
    image: alissonpereiraanjos/yue-exllamav2-interface:latest  # Docker image for YuE Interface
    container_name: yue-exllamav2-interface  # Name of the container
    restart: unless-stopped  # Restart policy: always restart unless manually stopped
    ports:
      - "7860:7860"  # Map port 7860 (Gradio UI) to the host
      - "8888:8888"  # Optional: Map an additional port (e.g., for other services)
    environment:
      - DOWNLOAD_MODELS=all  # Download all models. Replace "all" with specific model keys if needed.
                             # Example: DOWNLOAD_MODELS=YuE-s2-1B-general,YuE-s1-7B-anneal-en-cot
    volumes:
      - /path/to/models:/workspace/models  # Map the host's model directory to the container
      - /path/to/outputs:/workspace/outputs  # Map the host's output directory to the container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Enable GPU support (requires NVIDIA GPU and drivers)